[package]
name = "scrftch"
version = "0.1.0"
authors = ["Alexey Trifonov <avrong@outlook.com>"]
include = ["logos/*.html"]

[dependencies]
prettytable-rs = "0.6.7"
rust-ini = "0.11.0"
sys-info = "0.5.6"
psutil = "1.1.1"
lazy_static = "1.0.0"
